### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by XD-DENG** [XD-DENG/ECharts2Shiny#14]
@harryprince, please feel free to drop your suggestions here.

Thanks.

**Comment by harryprince** [comment]
I recommend you a post in here:https://segmentfault.com/a/1190000005922907
Dan is a top data analyst working on Alibaba group. He has a great idea about shiny, in that I recommend you to look this post. And here is his GitHub:https://github.com/danzhuibing

**Comment by XD-DENG** [comment]
I guess now I know what you mean in your email.

To interact with data from database, what we need is a complete shiny application. But this project is trying to embed interactive charts into shiny application. That is, this project is a R package, rather than a independent application. Or let's put it this way: this project is trying to replace the **plotly** package which was used in the example you shared with me.

But thanks for your sharing anyway.

**Comment by harryprince** [comment]
I suggest you have a great vision about data visualization design pattern, not only a wrapper for echarts. A new software architecture is critical that is how to separate query, CUBA, API, data table as an SOA is more important than integrated all things in one.
And when we plot charts in R, I hope I can get the query results  separated into data, SQL, API,and chart options. It will accelerate the result propagation, and the backend Go engineer and frontend Javascript developer and even DBA can participant in this project.

**Comment by harryprince** [comment]
Here is another Python version which has been made by Airbnb, this is my post link.
https://segmentfault.com/a/1190000005083953. Hope it will bring you an idea.

If the project is only another echarts wrapper, it means user should learn more option parameters like before..

**Comment by XD-DENG** [comment]
Sure. Thanks for your suggestions.

This project is simply a small project, with which I'm trying to tackle some practical problems I encountered in my daily work.

You're talking about something _big_, which is good. But 千里之行 始於足下. Even if the two posts you shared, they're built based on some other works, like some R packages. I'm trying to build an R package in this project, which can be used in something "big" in the future, as you desired.
