### ISSUE TITLE
Conflict Caused by Word Cloud Extension

### ISSUE THREAD

**Issue by XD-DENG** [XD-DENG/ECharts2Shiny#18]
As we're using a separate extension for word cloud feature, seems like it caused some conflicts with other charts. 

If we plot word clouds and other charts in one app, we get error.

**Comment by pissang** [comment]
Hi @XD-DENG  This bug has been fixed already in v1.0.1.

**Comment by XD-DENG** [comment]
@pissang Many thanks for the information!

**Comment by XD-DENG** [comment]
addressed with commit 5805b3d9425f98d6917aefb813ce939764d724aa
