### ISSUE TITLE
NA values in data.frame

### ISSUE THREAD

**Issue by yihengli** [XD-DENG/ECharts2Shiny#26]
It seems like if we have NA values in the data frame, the plots will not properly show up, though NA are originally supported by Echarts. Any ideas?

**Comment by XD-DENG** [comment]
Thanks for the feedback. I'll look into this.

May you kindly attach the code so that I can reproduce the error? Thanks!

**Comment by XD-DENG** [comment]
Hi @yihengli , I've preliminarily looked into this issue.

The reason is that this package would generate JS codes for generating charts. It converts `NA` values in R into `NA` too in javascript while javascript can only identify `null`.

My plan is to add one procedure in which we convert NA values into "null" so that it would work properly.

Will tag you once I submit the commit to address this issue. 

Thanks a lot.

**Comment by yihengli** [comment]
Thanks for the quick reply. I am also working on using echarts on R recently. (but mostly on R, I know not too much on Js) My first guess is also that Null may work instead of Na.

The package I recently use is https://github.com/yihui/recharts. Did you by any chance take a look before. Again, your project is a really beautiful work.

**Comment by XD-DENG** [comment]
Hi @yihengli , I've fixed this issue with commit c76f6eebc8b39bfc06389b08c646112b7f7d1810. This is a quick fix and may be not perfect. I will refine later.

My package is more like a pure wrapper of ECharts JS library. It can only be used within Shiny applications. This is a big limitation. But actually this also helped me make better use of the ECharts library. Pros and Cons, we always need to make some tradeoff.

Look forward to more feedbacks from you. Thanks!

**Comment by XD-DENG** [comment]
@yihengli sorry, I have missed YiHui's package `recharts` mentioned by you.
- Yihui's package is great. It was implemented by `htmlwidget` (if I'm not mistaken), so it can be used in more common R context. E.g., you can plot a chart with it just like using normal `plot` function. But as you may have noteiced, it can only support limited types of charts, like line charts and scatter charts.
- My package can only be used within **Shiny** application. This is the biggest shortage of my work. But it can support almost all the main charts, including **word cloud**. 

Another big difference is Yihui's package `recharts` used ECharts 2.2.3, and my package is using ECharts 3.

**Comment by yihengli** [comment]
@XD-DENG Haha, here are somethings I played around these days and will share with you. (FYI this hope something could help your work easier)
-  I replaced the js file under  `recharts/inst/htmlwidgets/lib/echarts/` with echarts3. Then it should support echarts3 without any problems.
- With the default functions, you are right, we cannot do many things there. But the `echart` function can handle a list like js option code. For example:

```
library(recharts)

charts.ch = list(
  title = list(
    text = 'test',
    subtext = 'test',
    x = 'center'
  ),
  tooltip = list(
    trigger = 'axis'
  ),
  legend = list(
    data = 'Test_group',
    x = 'right',
    orient = 'vertical'
  ),
  calculable = TRUE,
  dataZoom = list(
    list(
      type = 'slider',
      xAxisIndex = 0,
      show = TRUE,
      start = 0
    ),
    list(
      type = 'slider',
      left= '3%',
      yAxisIndex = 0,
      show = TRUE,
      start = 0,
      end = 100
    )
  ),
  xAxis = list (
    type = 'category',
    boundaryGap = FALSE,
    data = c('June 2016', 'July 2016')
  ),
  yAxis = list(
    type = 'value',
    axisLabel = list(
      formatter = '{value}'
    )
  ),
  series = list(
    name = 'Test_group',
    type = 'line',
    data = c(10,20),
    markPoint = list(
      data = list(
        list(type = 'max', name = 'MAX'),
        list(type = 'min', name = 'MIN')
      )
    ),
    markLine = list(
      data = list(list(yAxis = 15, name = 'AVG'))
    )
  )
)

echart(charts.ch)

```

In this way much more customization, though quite messy. And that's why when I saw your elegant way to do this I am really impressed and look forward to making it better and better.

**Comment by XD-DENG** [comment]
@yihengli The example you attached is cool.

Maybe setting default values carefully for your functions would help. 

Good luck to both of us ;-) Let's keep in touch. Maybe let me know once you've made more progress in the development of your package. I would be more than happy to help test your pacakge and hopefully give some feedbacks.

**Comment by yihengli** [comment]
@XD-DENG Lol, that's actually not developed by me. But yes, let's keep in touch. I will play around with your package recently and will hopefully give you more feedbacks. :)
