### ISSUE TITLE
Echarts2Shiny and Shinyapps.io

### ISSUE THREAD

**Issue by yihengli** [XD-DENG/ECharts2Shiny#31]
@XD-DENG 
Hi, wondering do you by any chance use or know shinyapps.io? I am currently using this platform for all my shiny apps. 

I recently used a package named "rsconnect" (https://github.com/rstudio/rsconnect) to deploy the code to their server. For any package installed from github, it should smoothly get installed from their server as well. 
`library(devtools)
install_github('XD-DENG/ECharts2Shiny')`

However, for ECharts2Shiny I got following message:

`Preparing to deploy application...DONE
Uploading bundle for application: 117613...DONE
Deploying bundle: 519952 for application: 117613 ...
Waiting for task: 220596791
  building: Parsing manifest
  building: Building image: 511546
  building: Building package: ECharts2Shiny
###### ########################### End Task Log #################################

Error: Unhandled Exception: Child Task 220596793 failed: Error building image: Error fetching ECharts2Shiny (0.1.5) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: ECharts2Shiny (0.1.5)`

For some reason, shinyapps still goes to CRAN to fetch this package instead of Github. (So version doen't match) I doubt if somewhere in the package force the installation to go that way? 

Alternatively, if I use `install.packages('ECharts2Shiny')`, the deployment will be no problem (for ver 0.1.2). Any advice?

**Comment by XD-DENG** [comment]
Hi @yihengli , thanks a lot for raising the issue. Actually another user mentioned the same issue as well. I guess it's possible that it's due to I specified "repository" field in **DESCRIPTION** file.

I've already done corresponding adjustments in commit 84c2850678236f918f09682c85e8c3330c5ac2ab. May you try again and let me know if it works? 

Thanks!

**Comment by yihengli** [comment]
@XD-DENG After this change, it works perfectly now. 

A lot of thanks. This does solve this issue.

**Comment by XD-DENG** [comment]
@yihengli Thanks for the feedback!

Additionally, as I'm rushing for the new version for publishing on CRAN, I've added the "slider" feature into line charts and scatter plots by myself in commit bda76fff9b97fcfb667ddee3de15ef578fcd88e5. But the idea did come from you.

I think it's necessary to add you into the contributor list. If you don't mind, may you do corresponding modifications in `DESCRIPTION` file and raise a pull request then? Thanks!
