### ISSUE TITLE
how to use connect option?

### ISSUE THREAD

**Issue by exitNA** [XD-DENG/ECharts2Shiny#43]
the echarts has connect options which can connect multi plot, does Echarts2Shiny support this feature?

**Comment by XD-DENG** [comment]
Hi, may you provide an example of the **connect** option in JavaScript? Or can you find it in the list of the offical examples http://echarts.baidu.com/examples.html and let me know the URL? 

Thanks.

**Comment by XD-DENG** [comment]
Not sure whether you mean the feature in this example? http://echarts.baidu.com/echarts2/doc/example/mix8.html

If yes, unfortunately, **ECharts2Shiny** doesn't support this option. But you can implement some similar chart with the widget provided by **Shiny**, which is also a more _R language_ way.

**Comment by exitNA** [comment]
hi:
this is the link http://echarts.baidu.com/api.html#echarts.connect of the connect.

**Comment by XD-DENG** [comment]
Hi,

Sorry this feature is not supported in the current version.

But your need can be solved if you use the same data.frame for different charts, so that all the charts will be updated concurrently if the data source is changed.

Please let me know if you need an example for this. Thanks.
