### ISSUE TITLE
ECharts2Shiny is conflict with shinydashboard

### ISSUE THREAD

**Issue by zhouq1986** [XD-DENG/ECharts2Shiny#49]
when I  ECharts2Shiny and want to use with shinydashboard
the ui code like this :+1: 
library(shiny)
library(shinydashboard)
library(ECharts2Shiny)
dashboardPage(
  # We HAVE TO to load the ECharts javascript library in advance
  loadEChartsLibrary()
  tags$div(id="test", style="width:80%;height:300px;"),
  deliverChart(div_id = "test")
)

the debug message is :+1:
Warning: Error in tagAssert: Expected tag to be of type header
Stack trace (innermost first):
    41: tagAssert
    40: dashboardPage
     1: runApp
Error in tagAssert(header, type = "header", class = "main-header") : 
  Expected tag to be of type header

**Comment by XD-DENG** [comment]
Hi @zhouq1986 , thanks for approaching!

May you provide a minimal re-producible code and share it as an R file with me through email? So that I can debug. my email address is xd.deng.r@gmail.com.

Thanks!

**Comment by XD-DENG** [comment]
Hi @zhouq1986 , in addition, may you share what version of R, Shiny and shinydashboard are you using? Thanks.

**Comment by XD-DENG** [comment]
Hi @zhouq1986 , I've tried to use ECharts2Shiny in shinydashboard. It does work. You need to put the statement `loadEChartsLibrary(),` in chunk `dashboardBody()`.

Please find the code sample I prepared. Have a try and let me know whether it works for you.

```R
library(shiny)
library(shinydashboard)
library(ECharts2Shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard"),
  
  dashboardSidebar(),
  
  dashboardBody(
    loadEChartsLibrary(),

    fluidRow(
      tags$div(id="test", style="width:80%;height:300px;"),
      deliverChart(div_id = "test")
    )
  )
)

server <- function(input, output) {
  
  dat <- data.frame(c(1, 2, 3, 1),
                    c(2, 4, 6, 6),
                    c(3, 2, 7, 5))
  names(dat) <- c("Type-A", "Type-B", "Type-C")
  row.names(dat) <- c("Time-1", "Time-2", "Time-3", "Time-4")
  
  renderBarChart(div_id = "test", grid_left = '1%',
                 data = dat)
}

shinyApp(ui, server)
```

**Comment by zhouq1986** [comment]
Yes，it works，thanks，ECharts2Shiny is verry useful for me !
I think I will have some other question for you .
zhouq

发件人: Xiaodong [mailto:notifications@github.com]
发送时间: 2017年5月1日 18:58
收件人: XD-DENG/ECharts2Shiny
抄送: 周强; Mention
主题: Re: [XD-DENG/ECharts2Shiny] ECharts2Shiny is conflict with shinydashboard (#49)


Hi @zhouq1986<https://github.com/zhouq1986> , I've tried to use ECharts2Shiny in shinydashboard. It does work. You need to put the statement loadEChartsLibrary(), in chunk dashboardBody().

Please find the code sample I prepared. Have a try and let me know whether it works for you.

library(shinydashboard)

library(ECharts2Shiny)



ui <- dashboardPage(

  dashboardHeader(title = "Basic dashboard"),



  dashboardSidebar(),



  dashboardBody(

    loadEChartsLibrary(),



    fluidRow(

      tags$div(id="test", style="width:80%;height:300px;"),

      deliverChart(div_id = "test")

    )

  )

)



server <- function(input, output) {



  dat <- data.frame(c(1, 2, 3, 1),

                    c(2, 4, 6, 6),

                    c(3, 2, 7, 5))

  names(dat) <- c("Type-A", "Type-B", "Type-C")

  row.names(dat) <- c("Time-1", "Time-2", "Time-3", "Time-4")



  renderBarChart(div_id = "test", grid_left = '1%',

                 data = dat)

}



shinyApp(ui, server)

**Comment by zhouq1986** [comment]
I works, thank you ! I am so glad that ECharts2Shiny can work with shinydashboard

**Comment by XD-DENG** [comment]
@zhouq1986 , good to hear this. Do let me know if any other issues encountered in the future.

Thanks again for your support to this package.
