### ISSUE TITLE
Error loading function "loadWordcloudExtension"

### ISSUE THREAD

**Issue by AbhishekHP2016** [XD-DENG/ECharts2Shiny#55]
loadWordcloudExtension() never loaded.
Error in loadWordcloudExtension() : 
  could not find function "loadWordcloudExtension"

Consequently Wordcloud is not displayed in Shiny Dashboard

**Comment by XD-DENG** [comment]
@AbhishekHP2016 Thanks for the feedback. May you provide a minimal example of your code? Cheers

**Comment by XD-DENG** [comment]
@AbhishekHP2016 may you check this example which is running properly? https://github.com/XD-DENG/ECharts2Shiny/blob/master/man/renderWordcloud.Rd#L62

In addition, I don't think I have any function called `loadWordcloudExtension()` in my package. Where did you get the information that asked you to include this function?
