### ISSUE TITLE
增强NA值的处理

### ISSUE THREAD

**Issue by ShixiangWang** [XD-DENG/ECharts2Shiny#57]
你好，

我在使用该包render条形图时发现NA值的处理不是很好。

为了符合函数的需要，我把数据转换成为了矩阵的形式

![image](https://user-images.githubusercontent.com/25057508/54679650-c7970a00-4b42-11e9-8b33-cc3683414be4.png)

实际上，某一列只有一行才有有值。虽然绘图显示的时候已经做好了处理，但条形图显示信息的时候还是会显示有NA值的。怎么去掉这些数据呢？

![image](https://user-images.githubusercontent.com/25057508/54679707-f1e8c780-4b42-11e9-81fb-8e32452b740e.png)

祝好，

诗翔

**Comment by XD-DENG** [comment]
诗翔你好。

很长时间没维护这个项目了，具体code的细节已经不记得。这有可能是底层js库的限制，也可能从R这一层上我们可以做一些处理。

最近我可能都不会有时间来进一步加强这一个项目。但如果你有兴趣的话，欢迎你raise PR，我会很乐意把它merge到下一个release里。

谢谢

**Comment by ShixiangWang** [comment]
@XD-DENG 好的，我尝试一下。谢啦~

**Comment by XD-DENG** [comment]
谢谢！let me know if you find anything unclear.

**Comment by ShixiangWang** [comment]
我仔细看了下源代码，尝试修改去掉显示信息的null值，但发现因为长度不一致，显示的时候数据和缺失值会自动往后移动。

![image](https://user-images.githubusercontent.com/25057508/54733313-fad5a980-4bd3-11e9-8e51-03d8f9390ae2.png)


测试数据和结果

![image](https://user-images.githubusercontent.com/25057508/54733324-0c1eb600-4bd4-11e9-8a93-ad79254c8701.png)

![image](https://user-images.githubusercontent.com/25057508/54733332-1b056880-4bd4-11e9-8513-a9e9ab1740df.png)

正确显示

![image](https://user-images.githubusercontent.com/25057508/54733367-425c3580-4bd4-11e9-9590-3749af3171f2.png)

（我想去掉Type-B的显示）

***

最后还是感谢回复，我看到 https://github.com/JohnCoene/echarts4r 更灵活些，暂时弃疗了~
