### ISSUE TITLE
Theme parameter of renderGauge() has no effect

### ISSUE THREAD

**Issue by stelmath** [XD-DENG/ECharts2Shiny#59]
Hello,

I am trying to add a Gauge and currently look at the manual for renderGauge. I notice that the suggested theme options ( "default", "roma", "infographic", "macarons", "vintage", "shine", "caravan", "dark-digerati", "jazz", and "london") produce the same result when I run the example from the manual:

```
if (interactive()) {
  library(shiny)
  library(ECharts2Shiny)
  
  
  # Server function -------------------------------------------
  server <- function(input, output) {
    # Call functions from ECharts2Shiny to render charts
    renderGauge(div_id = "test",rate = 99, gauge_name = "Finish Rate", theme = "dark-digerati")
  }
  
  # UI layout -------------------------------------------------
  ui <- fluidPage(
    # We MUST load the ECharts javascript library in advance
    loadEChartsLibrary(),
    
    tags$div(id="test", style="width:50%;height:400px;"),
    deliverChart(div_id = "test")
  )
  
  # Run the application --------------------------------------
  shinyApp(ui = ui, server = server)
}
```

Is this only me? I am trying to replicate the design found [here](https://echarts.baidu.com/echarts2/doc/example/gauge5.html#-en) that looks really awesome, but I can't. Thank you!

**Comment by stelmath** [comment]
Nevermind, I found about `loadEChartsTheme` in the documentation of ECharts2Shiny. I apologize for opening the issue, since this is not really an issue. Thanks for the awesome library!

**Comment by XD-DENG** [comment]
Thanks @stelmath for using my library and sharing the issue.
