### ISSUE TITLE
Data Labels in Echarts2Shiny

### ISSUE THREAD

**Issue by rubenzunguze** [XD-DENG/ECharts2Shiny#62]
I see the labels when I hover over the bars. However I would like to have a option to add printable labels on top or inside of the bars. Is it possible within this package?

Best,
Baptista

**Comment by XD-DENG** [comment]
Hi @rubenzunguze , Sorry for the late reply.

To my understanding this is not supported in the underlying ECharts library itself, hence not really feasible to support this.

**Comment by rubenzunguze** [comment]
Thank you. I imagined.

⁣Baptista Zunguze
Agribusiness Advisor
FDA - PROSUL
+258 870070017
Xai-Xai, Mozambique​
