### ISSUE TITLE
renderTreeMap doesn't accept JSON as data

### ISSUE THREAD

**Issue by damilolah** [XD-DENG/ECharts2Shiny#64]
Hi,

Thanks for your work.
According to the documentation, renderTreeMap should accept JSON data, however it doesn't. Even the examples used a JSON look alike: the keys have no quotes. How can I convert my JSON data whose keys have quotes to have no quotes like the one required by renderTreeMap?

**Comment by damilolah** [comment]
I resolved this using regex to remove all double quotes. It appears that renderTreeMap accepts only JSON formats with single quote keys labels and/or values labels. E.g.
`gsub("\"", "\'", json_data)`

**Comment by XD-DENG** [comment]
Thanks @damilolah .

Sorry I only noticed the notification just now, and happy to know you have resolved it! And appreciate adding your solution here so it may be helpful for other people as well.
